import type { Metadata } from "next";
import "./globals.css";
import Header from "./header";
import { UserProvider } from "./context/userContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout(
  { children, }: Readonly<{ children: React.ReactNode; }>
) {
  return (
    <html lang="en">
        <body className="antialiased">
        <UserProvider>
          <Header />
          <main>{children}</main>
        </UserProvider>
        </body>
    </html>
  );
}